In [1]:
import numpy as np

In [7]:
def printGame(gameBoard,level):
  print("__Level{}___\n".format(level))
  print('\n'.join([''.join(['{:3}'.format(item) for item in row]) 
      for row in gameBoard]))
  print('\n')

In [8]:
def legal_moves(board):
    """Create list of legal moves."""
    moves = []
    for i in range(len(board)):
        for j in range(len(board)):
            if board[i][j]==-1:
                moves.append((i, j))
    

    return moves

def TicTacToe(gameBoard):
    """
    ** YOU CODE SHOULDE PLAY AS PLAYER1
    gameBoard: 2D numpy array
    -1: empty cell
    0:  player0 marble is placed 
    1:  player1 marble is placed

    Number of each cell..
    -------------
    | 0 | 1 | 2 |
    | 3 | 4 | 5 |
    | 6 | 7 | 8 |
    -------------
    output: Number of the cell that you're going to place your marble. 
    """
    board = gameBoard[:]

     # if computer can win, take that move
    for move in legal_moves(board):
        board[move[0]][move[1]] = 1
        if checkWin(board) == 1:
            return move[1]+move[0]*3 
        # done checking this move, undo it
        board[move] = -1

    # if human can win, block that move
    for move in legal_moves(board):
        board[move[0]][move[1]]  = 0
        if checkWin(board) == 0:
            print(move)
            move[1]+move[0]*3
            return move[1]+move[0]*3
        # done checking this move, undo it
        board[move] = -1
    if (1,1) in legal_moves(board):
        return 4
    import random
    cellNum = random.choice ([i[1]+i[0]*3 for i in legal_moves(board)])
    return cellNum


#Q2

In [9]:
def row_win(board, player): 
    for x in range(len(board)): 
        win = True
          
        for y in range(len(board)): 
            if board[x, y] != player: 
                win = False
                continue
                  
        if win == True: 
            return(win) 
    return(win) 
  
# Checks whether the player has three 
# of their marks in a vertical row 
def col_win(board, player): 
    for x in range(len(board)): 
        win = True
          
        for y in range(len(board)): 
            if board[y][x] != player: 
                win = False
                continue
                  
        if win == True: 
            return(win) 
    return(win) 
  
# Checks whether the player has three 
# of their marks in a diagonal row 
def diag_win(board, player): 
    win = True
    y = 0
    for x in range(len(board)): 
        if board[x, x] != player: 
            win = False
    if win: 
        return win 
    win = True
    if win: 
        for x in range(len(board)): 
            y = len(board) - 1 - x 
            if board[x, y] != player: 
                win = False
    return win 
def checkWin(gameBoard):
    """
    gameBoard: 2D numpy array
    -1: empty cell
    0:  player0 marble is placed 
    1:  player1 marble is placed
    
    isWin: It should shows that if the game has a winner.
    winner: Acceptable values={0,1}. It should be equal to the winner id.
    """

    isWin = False
    winner = -1
    if row_win(gameBoard, 0) or col_win(gameBoard, 0) or diag_win(gameBoard, 0):
        winner = 0
        isWin = True
    elif row_win(gameBoard, 1) or col_win(gameBoard, 1) or diag_win(gameBoard, 1):
        winner = 1
        isWin = True
        

    #Write your code here

    if isWin:
        print("Winner Player is...{}".format(winner))
    return winner


In [13]:

gameBoard = np.ones(9,dtype=int).reshape((3,3))*-1
winner = -1
level =1
while -1 in gameBoard and winner == -1:
  player0 = input()
  try:
    player0 = int(player0)
    gameBoard[int(player0/3),player0%3] =0 
    printGame(gameBoard,level)
    level +=1
  except:
    print("Inter Integer Between 0,8")
    continue
  player1 = TicTacToe(gameBoard)
  gameBoard[int(player1/3),player1%3] = 1
  printGame(gameBoard,level)
  level +=1
  winner = checkWin(gameBoard)

print("Game Is Done...!!")

4
__Level1___

 -1 -1 -1
 -1  0 -1
 -1 -1 -1


__Level2___

 -1 -1 -1
 -1  0  1
 -1 -1 -1


0
__Level3___

  0 -1 -1
 -1  0  1
 -1 -1 -1


Winner Player is...0
(2, 2)
__Level4___

  0 -1 -1
 -1  0  1
 -1 -1  1


2
__Level5___

  0 -1  0
 -1  0  1
 -1 -1  1


Winner Player is...0
(0, 1)
__Level6___

  0  1  0
 -1  0  1
 -1 -1  1


6
__Level7___

  0  1  0
 -1  0  1
  0 -1  1


Winner Player is...0
Winner Player is...0
Winner Player is...0
(1, 0)
__Level8___

  0  1  0
  1  0  1
  0 -1  1


Winner Player is...0
Game Is Done...!!


#Q3

In [14]:
!wget http://archive.ics.uci.edu/ml/machine-learning-databases/00267/data_banknote_authentication.txt

--2021-03-06 12:30:44--  http://archive.ics.uci.edu/ml/machine-learning-databases/00267/data_banknote_authentication.txt
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 46400 (45K) [application/x-httpd-php]
Saving to: ‘data_banknote_authentication.txt.2’

data_banknote_authe 100%[===================>]  45.31K  81.8KB/s    in 0.6s    

2021-03-06 12:30:47 (81.8 KB/s) - ‘data_banknote_authentication.txt.2’ saved [46400/46400]



In [15]:
with open("data_banknote_authentication.txt") as file:
  f = file.read().split("\n")
  for i in range(len(f)):
    f[i] = f[i].split(",")
  data = np.array(f).astype(np.float64)
  y = data.T[-1]
  x = data.T[:4].T
  print("Number of records : ",len(data))
  print("The input : \n",x)
  print("The output : \n",y)

  ind = np.arange(len(y))
  np.random.shuffle(ind)
  x = x[ind]
  y = y[ind]
  k = (len(y) * 1) // 50
  x_train = x[:k]
  x_test = x[k:]
  y_train = y[:k]
  y_test = y[k:]


Number of records :  1372
The input : 
 [[  3.6216    8.6661   -2.8073   -0.44699]
 [  4.5459    8.1674   -2.4586   -1.4621 ]
 [  3.866    -2.6383    1.9242    0.10645]
 ...
 [ -3.7503  -13.4586   17.5932   -2.7771 ]
 [ -3.5637   -8.3827   12.393    -1.2823 ]
 [ -2.5419   -0.65804   2.6842    1.1952 ]]
The output : 
 [0. 0. 0. ... 1. 1. 1.]


In [16]:
#Implement your naive Bayes classifier for this dataset here (train on x_train and y_train, and predict on x_test to create y_pred).

class NaiveBayes:

    def calculate_req(self, x_train, y):
        samples_number, features_number = x_train.shape
        self.Lables = np.unique(y)
        self._mean = np.zeros((len(self.Lables), features_number))
        self._var = np.zeros((len(self.Lables), features_number))
        self._priors =  np.zeros(len(self.Lables))

        for idx, lable in enumerate(self.Lables):
            x_label = x_train[y==lable]
            self._mean[idx, :] = x_label.mean(axis=0)
            self._var[idx, :] = x_label.var(axis=0)
            self._priors[idx] = x_label.shape[0] / float(samples_number)

    def predict(self, x_test):
        y_pred=[]
        for x in x_test:
            posteriors = []

            for idx, c in enumerate(self.Lables):
                prior = np.log(self._priors[idx])
                
                mean = self._mean[idx]
                var = self._var[idx]
                num = np.exp(- (x-mean)**2 / (2 * var))
                denom = np.sqrt(2 * np.pi * var)
                
                posterior = np.sum(np.log( num / denom ))
                posteriors.append(prior + posterior)
            y_pred.append(self.Lables[np.argmax(posteriors)])
        return np.array(y_pred)
            
NaiveBayes = NaiveBayes()
NaiveBayes.calculate_req(x_train, y_train)
y_pred = NaiveBayes.predict(x_test)

In [17]:
from sklearn.metrics import classification_report
 
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.88      0.81      0.84       745
         1.0       0.78      0.87      0.82       600

    accuracy                           0.83      1345
   macro avg       0.83      0.84      0.83      1345
weighted avg       0.84      0.83      0.83      1345



In [18]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(x_train, y_train)
y_pr = (clf.predict(x_test))
print(classification_report(y_test, y_pr))

              precision    recall  f1-score   support

         0.0       0.88      0.81      0.84       745
         1.0       0.78      0.87      0.82       600

    accuracy                           0.83      1345
   macro avg       0.83      0.84      0.83      1345
weighted avg       0.84      0.83      0.83      1345



In [19]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(random_state=0).fit(x_train, y_train)
y_pre = (clf.predict(x_test))
print(classification_report(y_test, y_pre))

              precision    recall  f1-score   support

         0.0       1.00      0.94      0.97       745
         1.0       0.94      1.00      0.97       600

    accuracy                           0.97      1345
   macro avg       0.97      0.97      0.97      1345
weighted avg       0.97      0.97      0.97      1345

