In [9]:
import numpy as np
data = np.array([[29, 39, 75, 38, 35], [60, 31, 49, 27, 96], [48, 26, 13, 29, 90], [65, 97, 62, 34, 11], [46, 71, 76, 40, 87]])

# Batch Normalization

In [10]:
means = np.mean(data, axis=0)
variance_2 = np.var(data, axis=0)
variance = np.sqrt(variance_2)
print("means : ", means)
print("variance : ", variance)

batch_normalized= (data - means) / variance
print(batch_normalized)

means :  [49.6 52.8 55.  33.6 63.8]
variance :  [12.53156016 27.08800473 23.19482701  5.0039984  34.28935695]
[[-1.64384959 -0.50945059  0.86226123  0.87929684 -0.83991076]
 [ 0.82990465 -0.80478427 -0.25867837 -1.31894527  0.9390669 ]
 [-0.12767764 -0.98936781 -1.81074858 -0.91926488  0.76408549]
 [ 1.22889726  1.63171856  0.30179143  0.07993608 -1.5398364 ]
 [-0.28727469  0.67188411  0.90537429  1.27897723  0.67659478]]


# Layer Normalization

In [11]:
means = np.mean(data, axis=1)
variance_2 = np.var(data, axis=1)
variance = np.sqrt(variance_2)
print("means : ", means)
print("variance : ", variance)

layer_normalized= (data - means) / variance
print(layer_normalized)

means :  [43.2 52.6 41.2 53.8 64. ]
variance :  [16.27759196 24.79193417 26.84324869 29.26704631 18.01110768]
[[-0.87236491 -0.54856551  1.25916205 -0.53985632 -1.61011752]
 [ 1.03209369 -0.8712511   0.29057586 -0.91570566  1.7766814 ]
 [ 0.29488391 -1.0729296  -1.05054348 -0.84736942  1.44355364]
 [ 1.33926444  1.79090505  0.77486895 -0.67652881 -2.94262857]
 [ 0.17201562  0.74217687  1.29641536 -0.47152008  1.27698976]]
